#!/bin/sh
#
# The hook should exit with non-zero status after issuing an appropriate
# message if it wants to stop the commit.

./setupEnv.py

sed -ri "s/^(# Timestamp: )(.*)/\1`date`/" source/main.appcache
git add source/main.appcache

CMD_NAME=`basename $0`

if [ -f $GIT_DIR/hooks/custom/${CMD_NAME} ]
then
    if ! $GIT_DIR/hooks/custom/${CMD_NAME} $@
    then
        # kill this script if it fails
        exit 1
    fi
fi

exit 0
